//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECCION_GOMAS
    {
        public int ID { get; set; }
        public Nullable<int> ID_INSPECCION { get; set; }
        public Nullable<bool> GOMA_TRASERA_DERECHA { get; set; }
        public Nullable<bool> GOMA_TRASERA_IZQUIERDA { get; set; }
        public Nullable<bool> GOMA_DELANTERA_DERECHA { get; set; }
        public Nullable<bool> GOME_DELANTERA_IZQUIERDA { get; set; }
        public string DESCRIPCION { get; set; }
        public string CODE { get; set; }
    
        public virtual INSPECCION INSPECCION { get; set; }
    }
}
